// Generated by https://quicktype.io

export interface Patient {
    resourceType:         string;
    id:                   string;
    text:                 Text;
    identifier:           Identifier[];
    active:               boolean;
    name:                 Name[];
    gender:               string;
    photo:                Photo[];
    contact:              Contact[];
    managingOrganization: Organization;
    link:                 Link[];
    meta:                 Meta;
}

export interface Contact {
    relationship: Type[];
    organization: Organization;
}

export interface Organization {
    reference: string;
    display:   string;
}

export interface Type {
    coding: Coding[];
}

export interface Coding {
    system: string;
    code:   string;
}

export interface Identifier {
    use:    string;
    type:   Type;
    system: string;
    value:  string;
}

export interface Link {
    other: Other;
    type:  string;
}

export interface Other {
    reference: string;
}

export interface Meta {
    tag: Tag[];
}

export interface Tag {
    system:  string;
    code:    string;
    display: string;
}

export interface Name {
    use:    string;
    family: string;
    given:  string[];
}

export interface Photo {
    contentType: string;
    data:        string;
}

export interface Text {
    status: string;
    div:    string;
}
